src/lib/quoteEngine.js

Changing default values from 0 to `Zero`

FIX: Surge calculation fail

---

src/lib/capacityEngine.js
src/lib/quoteEngine.js
src/routes/capacity.js
src/routes/quote.js

Returning status 400 for non-existing product

Fix: return 400 on invalid product

---

src/lib/quoteEngine.js
src/routes/quote.js

Issue: #21 
Quote route expanded with:
- error if there is no capacity for the cover amount
- capacities of the pools for the quote

Route adjustment

---

src/lib/constants.js
src/lib/eventsApi.js
src/lib/helpers.js
src/lib/synchronizer.js

There is no tracker for bucket expiration and bucket change
Adding interval function check if there is a bucket expiration, and listener so we can update all the pools and products with new data

Feature: bucket change event

---

src/config.js
src/lib/helpers.js
src/lib/synchronizer.js

Issue: #18
Add helper function to execute async function in batches and use it in initial sync

Add batching helper function and use it at the start sync

---

src/lib/chainApi.js
src/lib/quoteEngine.js
src/routes/quote.js

Issue: #40 
Extend product data in store with `isDeprecated` prop and use it to check when quote is requested

Add isDeprecated check before sending the quote

---

src/routes/quote.js
test/unit/responses.js

[FE issue](https://github.com/NexusMutual/frontend-react/issues/1445)
Adding calculation to quote route for the annual price. The value is returned as an integer with a denominator value of 100.

Add annual price to quote

---

src/lib/chainApi.js

Change chain api  to use `getInternalTokenPriceInAsset` in `fetchTokenPriceInAsset`

Fix token price call in chain API

---

src/lib/capacityEngine.js

Issue: #64  
- Removing max function when calculating capacity
- Fix starting index for capacity calculation

Fix capacity calculation

---

src/lib/constants.js
src/lib/quoteEngine.js
test/unit/calculateOptimalPoolAllocation.js
test/unit/quoteEngine.js

Issue: #71  
- Switch from chunking the amount by a fixed amount to chunking it by capacity and it's price
- WIP

Change the way we batch allocations for quote calculation

---

src/index.js
src/lib/synchronizer.js
src/routes/reindex.js
src/store/cache.js
src/store/index.js
src/store/reducer.js
storage/.gitignore
test/unit/cache.js
test/unit/calculateOptimalPoolAllocation.js
test/unit/index.js

Issue: #73 
Cache the internal state for a faster startup. 

Implement state caching

---

package-lock.json
package.json

New version of contracts were deployed
Bump `@nexusmutual/deployments` to 2.6.1
N/A

chore: Bump `@nexusmutual/deployments` to 2.6.1

---

.eslintrc
.github/workflows/checks.yml
.gitignore
.husky/pre-push
package-lock.json
package.json
src/index.js
src/lib/capacityEngine.js
src/lib/contracts.js
src/lib/eventsApi.js
src/lib/quoteEngine.js
src/lib/swagger.js
src/lib/synchronizer.js
src/routes/capacity.js
src/routes/quote.js
src/routes/reindex.js
src/store/cache.js
src/store/index.js
test/mocks/server.js
test/unit/cache.js
test/unit/calculateOptimalPoolAllocation.js
test/unit/capacityEngine.js
test/unit/eventApi.js
test/unit/quoteEngine.js
test/unit/routes/capacity.js
test/unit/routes/quote.js

Add missing CI, pre-push hook and update .eslintrc rules to align with all our backend services repos
NOTE:
no code changes aside from linting fixes (mostly import ordering fixes)
* add CI lint and test
* add pre-push git hook
* update .eslintrc rules and fix linting issues
manual test

chore: Add CI lint and test + pre-push git hook

---

README.md

Fix URL in README and add openapi URL links
* Fix URL in README
* add openapi URL links in README
N/A

docs: Fix README URL + add openapi links

---

package-lock.json
package.json
src/lib/chainApi.js
src/lib/eventsApi.js
test/unit/eventApi.js
test/unit/responses.js

Issue: #96 
Change ChainAPI and EventAPI libs to support changes made on the protocol (CoverProducts)

feat: Add support for CoverProducts

---

.dockerignore
.github/workflows/checks.yml
Dockerfile
test/unit/responses.js

Include relevant motivation and context. A link to the issue is enough if it contains all the relevant 
information.
Include a summary of the change.

integrate cicd

---

package-lock.json
package.json

Update @nexusmutual/deployments to 2.8.0
Update @nexusmutual/deployments to 2.8.0

chore: Update @nexusmutual/deployments to 2.8.0

---

.github/workflows/checks.yml
README.md

Include relevant motivation and context. A link to the issue is enough if it contains all the relevant 
information.
Include a summary of the change.

Sync CI/CD changes

---

package-lock.json
package.json

Update deployments package to v2.9.0

chore: update @nexusmutual/deployments to 2.9.0

---

.github/workflows/checks.yml
.husky/commit-msg
.husky/pre-commit
.husky/pre-push
commitlint.config.js
package-lock.json
package.json
src/config.js
src/store/reducer.js
test/mocks/store.js
test/unit/reducer.js

- Update @nexusmutual/deployments to 2.9.0
- Add semantic commit branch git hooks validation
- Add custom priority pools env auto read, parse and apply
- remove trivy scan from the ci 

chore: package update + semantic validation + custom priority pools env auto read

---

package-lock.json
package.json

chore: update cover-router version tp 2.3.7

---

.github/workflows/ff-release-candidate-to-master.yml
.github/workflows/merge-to-dev.yml
.github/workflows/merge-to-master.yml

Add new workflows:
- merge-to-dev
- merge-to-master
- ff-release-candidate-to-master
All the testing was done on the dummy app

chore: new workflows

---

package-lock.json
package.json

Removing version bump from dev branch so there are no conflicts when there is a rebase

fix: revert version to be the same as master so there are no conflicts

---

package-lock.json
package.json

Describe the changes made in this PR. A link to the issue is enough if it contains all the relevant information.

fix: upgrade deployments package

---

src/lib/chainApi.js

Describe the changes made in this PR. A link to the issue is enough if it contains all the relevant information.

fix: mock product type call for product type id 2

---

src/lib/chainApi.js

Describe the changes made in this PR. A link to the issue is enough if it contains all the relevant information.

fix: fix bad product type fix

---

package-lock.json
package.json
src/lib/eventsApi.js
test/unit/eventApi.js

Changed CoverEdited event to CoverBought

fix: change CoverEdited event to CoverBought

---

src/lib/quoteEngine.js
test/unit/responses.js

Describe the changes made in this PR. A link to the issue is enough if it contains all the relevant information.

fix: add a round up on annual price calculation
