NexusMutual/cover-router

- src/lib/eventsApi.js
Adding `ProductUpdated` event listener on StakingProducts contract
> fix: ProductUpdated event missing in the EventsApi

- src/routes/quote.js
Context:
Some of the poolIds are being returned as BigNumber
Solution:
Before sending the response call `toString()` on poolId
> Fix poolId not a string

- src/lib/capacityEngine.js
- src/routes/capacity.js
- test/unit/capacityEngine.js
- test/unit/responses.js
UI needs used capacities for the products so they can sort it by popularity.
Issue: #31 
Added `capacityUsed` calculation to the capacityEngine and added it to response on capacity endpoints
Edited tests to check the capacityUsed prop
> Feature: Adding usedCapacity to capacity response

- src/lib/constants.js
- src/lib/quoteEngine.js
- test/unit/calculateOptimalPoolAllocation.js
- test/unit/utils.js
When making a request to buy 2500 ETH on balancer the router is not able to find an allocation.
```{
poolId: 1,
poolCapacityUsed: '0',
amountToAllocate: '8860',
totalCapacity: '7228'
}
CANNOT
{
poolId: 2,
poolCapacityUsed: '0',
amountToAllocate: '8860',
totalCapacity: '8390'
}
CANNOT
{
poolId: 3,
poolCapacityUsed: '64761',
amountToAllocate: '8860',
totalCapacity: '68382'
}
CANNOT
{
poolId: 4,
poolCapacityUsed: '18073',
amountToAllocate: '8860',
totalCapacity: '23242'
}
CANNOT
```
A test case is written to capture this specific production setup to prove allocation now works given the fix.
With a 10% chunk size it hits a pathological case where it cannot utilize the capacity (units don't fit in the existing gaps).
Reducing size to 1%.
> reduce unit size to 1%

- src/lib/constants.js
The value of the PRICE_CHANGE_PER_DAY param in the Cover.sol contract has been updated from 0.5% to 2% in this proposal: https://app.nexusmutual.io/governance/view?proposalId=213. This hasn't been reflected in the cover router code. This PR fixes this.
There is an argument to be made that these values should be read from the contract instead of being hardcoded.
Update PRICE_CHANGE_PER_DAY constant from 0.5% to 2%.
Checked the price for Balancer is close to 4% annual, as explained on slack in the bug report.
* :thinking: = I don’t understand something, do …
> fix: Update PRICE_CHANGE_PER_DAY to reflect onchain value

- README.md
- package-lock.json
- package.json
- src/lib/capacityEngine.js
- src/lib/chainApi.js
- src/lib/quoteEngine.js
- src/lib/synchronizer.js
- src/routes/capacity.js
- src/routes/quote.js
- src/store/cache.js
- src/store/reducer.js
- src/store/selectors.js
- test/mocks/store.js
- test/unit/cache.js
- test/unit/capacityEngine.js
- test/unit/quoteEngine.js
- test/unit/responses.js
- test/unit/routes/quote.js
Issue: #83 
- Add USDC as a asset to the store
- Add caching overwrite for constants
- remove comments regarding support for the decimals, because PriceFeedOracle returns rates in asset units
- add asset object to `/quote`, `/capacity` and `/capacity/{productId}` responses
- update openapi docs
`/quote`
```json
{
"quote": {
"totalCoverAmountInAsset": "string",
"annualPrice": "string",
"premiumInNXM": "string",
"premiumInAsset": "string",
"poolAllocationRequests": [
{
"poolId": "string",
"coverAmountInAsset": "string",
"skip": false
}
],
"asset": { // <--- new asset field
"id": "string",
"symbol": "string",
"decimals": 18
}
},
"capacities": [
{
"poolId": "string",
"capacity": [
{
"assetId": "string",
"amount": "string",
"asset": { // <--- new asset field
"id": "string",
"symbol": "string", …
```
> feat: Add USDC support

- package-lock.json
- package.json
- src/routes/capacity.js
- src/routes/quote.js
- src/store/reducer.js
- test/mocks/store.js
- test/unit/responses.js
open-cover asked why `asset.id` was string and if we would support input of assetId as string.
looking at our smart-contracts it seems we take in assetId as a number `Pool.getAsset(uint assetId)`. So maybe we should enforce that all assetId should be in number format.
Although this is technically a breaking change, since open-cover is the only consumer for now and this was only released earlier today maybe we can fix it otherwise we'll be stuck with this inconsistency.
* change `asset.id` to number
* update openapi docs
* update test expectations for `asset.id` to be a number
* :hammer: = I believe …
> fix: Convert assetId to number

- src/routes/quote.js
I missed changing one `asset.id` to number in openapi docs 🤦‍♂️
* change openapi docs /quote `asset.id` to number
* manually ran the openapi docs locally and verified ALL `asset.id` are integers
> fix: Fix openapi /quote asset.id docs

- src/lib/quoteEngine.js
- test/unit/calculateOptimalPoolAllocation.js
- test/unit/customAllocationPriorityFixedPrice.js
Currently when there is capacity we return the allocation object, but if there is not enough capacity we return an empty array.
The return value should be consistent, hence changing it to empty object.
* change return value to empty object on not enough capacity
* fix unit tests
> refactor: Change no capacity return value to empty object

- package-lock.json
- package.json
- src/store/reducer.js
Add Dialectic Moonphase / Chronograph custom priority pools:
* We should configure the cover router to source capacity in the following order of pools: 1, 23, 22, 2, 5
https://nexusmutual.slack.com/archives/C076V9H4ND7/p1719411773569079
* Add Dialectic Moonphase / Chronograph custom priority pools
* 1, 23, 22, 2, 5
* :thinking: = I don’t understand something, do you mind giving me …
> feat: Add custom pool priority for Dialectic Moonphase and Chronograph

- package-lock.json
- package.json
- src/lib/quoteEngine.js
- test/unit/customAllocationPriorityFixedPrice.js
it mutates the reducer state so subsequent calls have empty custom priority pools array which causes it to fail
* fix bug
* manual test locally
> fix: Fix custom priority pools order bug

- src/config.js
- src/lib/quoteEngine.js
(I thought I pushed this change earlier but it seems I pushed AFTER the PR got merged so it was not included)
It's safer to throw if we forget to add the necessary env vars because we're alerted straight away that it's missing.
Returning an empty array obfuscates the missing env var issue and it will fail later with "not enough capacity" and it's not easy to see that the root cause was a missing env var.
* throw error if array-int env var is missing
* change warn log to info
N/A
* :thinking: = I don’t understand something, do you mind giving me more …
> refactor: Throw error if array-int env var value is missing

- src/lib/capacityEngine.js
- src/lib/constants.js
When calculating the max price we used hardcoded number of for the loop whitch was 5 as it covers more then a year cover period but if the current branch is at the end and we add grace period to the cover period it also can go to the 6th tranche
Add calculation for the max period tranche id to be used in the capacity calculation instead of the hardcoded count
* :thinking: = I …
> Fix: use max period tranche id instead of hardcoded number in the loop

- package-lock.json
- package.json
- src/config.js
- src/store/reducer.js
Relates to https://github.com/NexusMutual/sdk/issues/208
Custom Pools Priority Ordering:
The below env vars needs to be added to cover-router env vars
```
PRIORITY_POOLS_ORDER_227=8,23,22,2,1,5
PRIORITY_POOLS_ORDER_233=22,2,1,23
```
* updated to read the new priority pools ordering env vars
Tested locally on product 227 and logged the state:
```javascript
productPriorityPoolsFixedPrice:  {
'186': [ 18, 22, 1 ],
'195': [ 1, 23, 22, 2, 5 ],
'196': [ 1, 23, 22, 2, 5 ],
'227': [ 8, 23, 22, 2, 1, 5 ],
'233': [ 22, 2, 1, 23 ]
}
```
inspected the quote allocations:
```json
"poolAllocationRequests": [
{
"poolId": "2",
"coverAmountInAsset": "368628193797905307586", (87% of capacity)
"skip": false
},
{
"poolId": "8",
"coverAmountInAsset": "363264412514561374629", (99% of capacity)
"skip": false
}, …
```
> chore: add new priority pools ordering

- package-lock.json
- package.json
- src/config.js
- src/store/reducer.js
- test/mocks/store.js
- test/unit/reducer.js
Closes #126
Currently when adding custom priority pool env vars `PRIORITY_POOLS_ORDER_XXX` we need to also manually add code to read these and apply them.
This change removes that manual step so we can just add the new custom priority pools env vars and restart the service (reading, parsing and applying of these env vars will be done automatically)
* auto read, parse and apply of custom priority pools order env vars
* added unit tests
> feat: add custom priority pools env auto read, parse and apply

- .github/workflows/checks.yml
The CI scan step is erroring out too often and it's not required as we're using GH's dependabot.
N/A.
> chore: remove trivy scan from the ci

- README.md
- src/lib/capacityEngine.js
- src/routes/capacity.js
- test/unit/capacityEngine.js
- test/unit/responses.js
- test/unit/routes/capacity.js
Closes https://github.com/NexusMutual/cover-router/issues/131
`/capacity/:pooId`:
* new `capacityPerPool` field object - min/maxAnnualPrice for a product per pool 
NOTE: this PR is behind https://github.com/NexusMutual/cover-router/pull/130
unit tests
> feat: add new field capacityPerPool to capacity pool API

- src/lib/capacityEngine.js
- src/routes/capacity.js
- test/unit/routes/capacity.js
For pool 28, which has 0 products, `cover-router` currently returns a 404 `PoolId not found`.
This happens because `cover-router` only tracks which poolIds support which products. It doesn’t distinguish between an invalid poolId and a pool with no products, so it responds the same way in both cases.
Given that we have a valid pool (28) with 0 products, and the FE is unlikely to query cover-router with an invalid poolId, it makes sense to adjust the response to better reflect the scenario of pools with no products.
This PR implements those changes.
unit tests
> refactor: return empty product capacity on pools with no products

- src/lib/capacityEngine.js
- src/lib/helpers.js
- src/lib/quoteEngine.js
- src/routes/quote.js
- test/unit/calculatePoolAllocations.js
- test/unit/capacityEngine.js
- test/unit/helpers.js
- test/unit/pricingEngine.js
- test/unit/quoteEngine.js
- test/unit/responses.js
- test/unit/utils.js
Closes #168, Closes #169, Closes #170
- Moving calculation of available capacity to one place (in helpers) to be used by both `capacityEngine` and `quoteEngine`.
- `calculatePoolAllocation` is refactored to return an array instead of object, and `quoteEngine` now returns pools in the same priority order as allocation is taken. 
Fixed unit tests, and rewrote calculatePoolAllocation tests.
> fix: available capacity calculation

- src/lib/quoteEngine.js
- src/routes/capacity.js
- src/routes/quote.js
- test/unit/responses.js
Removed `availableCapacity` and `capacitiesPerPool` from the quote route since we now can get it from the capacity route with edited cover accounted as well.
> fix: remove capacities response from the quote route
